COPY_EXISTING ~profs.2da~ ~override~
  READ_2DA_ENTRIES_NOW ~tb#profs.2da_read~ 3
  FOR (i = 0; i < tb#profs.2da_read; ++i) BEGIN
	READ_2DA_ENTRY_FORMER ~tb#profs.2da_read~ i 1 start
	READ_2DA_ENTRY_FORMER ~tb#profs.2da_read~ i 2 interval
	PATCH_IF start < 2 BEGIN
		SET_2DA_ENTRY_LATER ~tb#profs.2da_set~ i 1 2
	END
	PATCH_IF interval > 3 BEGIN
		SET_2DA_ENTRY_LATER ~tb#profs.2da_set~ i 2 3
	END
  END
  SET_2DA_ENTRIES_NOW ~tb#profs.2da_set~ 3
BUT_ONLY
